### ISSUE TITLE
CCCamp

### ISSUE THREAD

**Issue by emanuelduss** [optikfluffel/35c3.info#24]
Hey Udo

Do you have plans to do this project for the CCCamp 2019 as well?

Grz,
Mänu

**Comment by optikfluffel** [comment]
Hey Mänu, I don't think so. Mainly because I most certainly won't be able to make it to Camp (not enough tickets etc. 🤷‍♂️), but if you want to do it I'd be willing to help you set it up.

PS: I also already have camp2019.info, which you could of course use for free.

**Comment by emanuelduss** [comment]
Hey Udo

Ah, sad :(

I would do it. I guess when the site works once, the only work is to merge pull requests, right?

I would appreciate if you would help me set it up. I do not really understand how it works at the moment (all I see that site is hosted on GitHub pages somehow according to the IP address but shouldn't there be a node server somewhere?).

So, it would be really cool if you would help to understand it and set it up. :smile: 

Thanks & best regards,
Emanuel

**Comment by optikfluffel** [comment]
The camp website will be developed at [gitlab.com/optikfluffel/camp2019.info](https://gitlab.com/optikfluffel/camp2019.info).
