### ISSUE TITLE
Add (Fav-) Icons

### ISSUE THREAD

**Issue by optikfluffel** [optikfluffel/35c3.info#3]
__Icons are still missing from the page.__

I'd suggest using [realfavicongenerator.net](https://realfavicongenerator.net) with a `png` file, with at least `512px x 512px` dimensions. Since @JimFrostig already helped me getting `src/images/circuit.svg` right, this would be a perfect task for him. 😋

**Comment by JimFrostig** [comment]
ok i do it 👍  😄

**Comment by JimFrostig** [comment]
![circuit](https://user-images.githubusercontent.com/6785519/49037317-3201f400-f1ba-11e8-991c-eef519c4c3c9.png)
here u go with your new fresh icon 😸
